"""add users and interactions

Revision ID: 06797c060046
Revises: fd7484a41540
Create Date: 2026-10-02 21:33:57.584309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06797c060046'
down_revision: Union[str, Sequence[str], None] = 'fd7484a41540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('interactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_type = 'search' AND query_text IS NOT NULL AND experience_id IS NULL) OR (event_type <> 'search' AND experience_id IS NOT NULL AND query_text IS NULL)", name=op.f('ck_interactions_event_shape')),
    sa.CheckConstraint("event_type IN ('view', 'click', 'save', 'unsave', 'like', 'unlike', 'dislike', 'search', 'complete', 'skip')", name=op.f('ck_interactions_event_type_valid')),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('fk_interactions_experience_id_experiences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index('ix_interactions_experience_id_event_type', 'interactions', ['experience_id', 'event_type'], unique=False)
    op.create_index('ix_interactions_user_id_occurred_at', 'interactions', ['user_id', 'occurred_at'], unique=False)
    # Existing rows get now() as created_at via the server default.
    op.add_column('experiences', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Redundant: the primary key already has its own unique index.
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    # ### end Alembic commands ###

    # Added by hand: autogenerate does not compare server defaults.
    # Lets the database (not only the ORM) fill in cost = 0.
    op.alter_column('experiences', 'cost', server_default='0')


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('experiences', 'cost', server_default=None)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.drop_column('experiences', 'created_at')
    op.drop_index('ix_interactions_user_id_occurred_at', table_name='interactions')
    op.drop_index('ix_interactions_experience_id_event_type', table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('users')
    # ### end Alembic commands ###
